name: Monkeytype Readme

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  update-readme:
    name: Update README
    runs-on: ubuntu-latest
    steps:
      - uses: vnphanquang/monkeytype-readme@main
        with:
          monkeytype_api_key: ${{ secrets.MONKEYTYPE_API_KEY }}
          mode: 'time'
          mode2: '60'
          style: 'for-the-badge'
          logoVariant: 'one'
          label: 'monkeytype'
